#ifndef __aisTX_appPanelMain__
#define __aisTX_appPanelMain__

/**
@file
Subclass of PanelMain, which is generated by wxFormBuilder.
*/
#include <wx/msgdlg.h>
#include <wx/calctrl.h>
#include <wx/font.h>
#include <wx/colour.h>
#include <wx/settings.h>
#include <wx/string.h>
#include <wx/button.h>
#include <wx/stattext.h>
#include <wx/textctrl.h>
#include <wx/sizer.h>
#include <wx/panel.h>
#include <wx/math.h>
#include <wx/vector.h>
#include <wx/progdlg.h>
#include <wx/timectrl.h>

#include <wx/artprov.h>
#include <wx/xrc/xmlres.h>
#include <wx/intl.h>
#include <wx/gdicmn.h>
#include <wx/filepicker.h>
#include <wx/settings.h>
#include <wx/statbox.h>
#include <wx/dialog.h>
#include <wx/fileconf.h>
#include <wx/datetime.h>
#include <wx/choice.h>
#include <wx/cmdline.h>
#include <wx/datetime.h>
#include "wx/stdpaths.h"
#include <wx/filename.h>
#include <wx/fileconf.h>
#include <wx/process.h>
#include <wx/timer.h>


#define wxID_START        101
#define wxID_END    102

class wxFileConfig;
class CalendarDialog;
class AisMaker;
class SimpleSerial;

#include "aisTX_appUI.h"
#include "SimpleSerial.h"
#include "AisEncoder.h"
#include "AisMaker.h"
#include "listports.h"
#include "portsEnum.h"

//// end generated include

/** Implementing PanelMain */
class aisTX_appPanelMain : public PanelMain
{
	protected:
		// Handlers for PanelMain events.
		void OnAbout(wxCommandEvent& event);
		void OnStart(wxCommandEvent& event);
		void OnStop(wxCommandEvent& event);
		int StartDriving();
		void OnTimer(wxTimerEvent& event);
		wxString GetMessage();
		char* GetComPort(int port_aux);
		DWORD GetBaudRate(int rate);

	public:
		/** Constructor */
		aisTX_appPanelMain( wxWindow* parent );
	//// end generated class members
		char output[255];
		const char* port = "COM8";
		std::string AisParts[8];
		std::string AisMsg = "";
		std::string MSG = "";
		int DAC = 0;
		int FI = 0;
		std::string payloadText = "";
		int n;
		unsigned char buf[4096];
		int port_nr;
		int baudrate = 9600;
		//unsigned char outBuffer[128];
		std::string outBuffer;
		string comports[10];
		int portnum; // Number of available ports
		AisMaker myAIS;
		SimpleSerial* mySerial;
		DWORD COM_BAUD_RATE = CBR_4800;

	private:
		//wxString m_sDummy;
		wxFileConfig   *m_pconfig;	
		wxString script_string;
		wxString m_sConfigDir;
		wxString m_sMotuClientDir;
		wxString m_sArea;
		wxString m_sUserName;
		wxString m_sUserPassword;
		wxString m_sMotuServer;
		wxString m_sMyOceanDataset;
		wxString m_sMyOceanForecast;
		wxString m_sLatMin;
		wxString m_sLatMax;
		wxString m_sLonMin;
		wxString m_sLonMax;
		wxString m_sTimeStart;
		wxString m_sTimeEnd;
		wxString m_sVcurr;
		wxString m_sUcurr;
		wxString m_sOutputDir;
		wxString m_sOutputFile;
		std::string serialOut;
		char* charArray;

		wxString myNMEAais44_8;

		bool LoadConfig(void);
		void OnStartScript(wxCommandEvent& WXUNUSED(event));
		

};

class CalendarDialog : public wxDialog
{
public:

	CalendarDialog(wxWindow * parent, wxWindowID id, const wxString & title,
		const wxPoint & pos = wxDefaultPosition,
		const wxSize & size = wxDefaultSize,
		long style = wxDEFAULT_DIALOG_STYLE);

	wxCalendarCtrl* dialogCalendar;
	wxStaticText *m_staticText;
	wxTimePickerCtrl *_timeCtrl;

private:

};


#endif // __aisTX_appPanelMain__
