#ifndef __aisTX_appFrameMain__
#define __aisTX_appFrameMain__

/**
@file
Subclass of FrameMain, which is generated by wxFormBuilder.
*/

#include "aisTX_appUI.h"

//// end generated include

/** Implementing FrameMain */
class aisTX_appFrameMain : public FrameMain
{
	public:
		/** Constructor */
		aisTX_appFrameMain( wxWindow* parent );
	//// end generated class members



};

#endif // __aisTX_appFrameMain__
